### PR TITLE
BRS-896: Add winterWarning field to writeFacility lambdas

### PR DESCRIPTION
**Pull request by wilwong89**
BRS-896: Add winterWarning field to writeFacility lambdas

### Jira Ticket:

BRS-896

### Jira Ticket URL:

https://bcparksdigital.atlassian.net/browse/BRS-896

### Description:

Update lambdas to handle winter waiver flag, update facility with winter warning flag.

### CODE REVIEW

**Review by cameronpettit — COMMENTED** [review]
A couple of things I am hesitant about here:
1. There is no migration script to update the `facilites` objects. Yes, we can go through and save  every facility in every park in every environment once and the changes should take effect, but we should be relegating that work to a script in case we need to back out of the migration and restore from a backup. 
2. I'm not sure this is the way we want to be implementing our feature flagging. Do we want each facility to have its own `winterWarning` flag, that we have to go in and toggle each season change on each individual facility? Or is this a site-wide configuration flag, where we only have to toggle it once in one spot at the beginning of winter, and then EVERY facility has the winter warning text? The ticket isn't super clear on this but I don't feel comfortable updating our `facility` object schema just to flag some front end text that may very well identical site-wide. It will scale poorly the more facilities we have in our system.

**Comment by wilwong89** [comment]
> A couple of things I am hesitant about here:
> 
> 1. There is no migration script to update the `facilites` objects. Yes, we can go through and save  every facility in every park in every environment once and the changes should take effect, but we should be relegating that work to a script in case we need to back out of the migration and restore from a backup.

The frontends right now assume that if the facility objects does not have the `winterWarning` field then it assumes it is false. So it's not necessary to go out of the way to save through every facility to add the flag for the feature to work. It will eventually get added to all the objects over time. If a restore from backup is necessary then at worst it means we will need to re-enable to flags.

> 2. I'm not sure this is the way we want to be implementing our feature flagging. Do we want each facility to have its own `winterWarning` flag, that we have to go in and toggle each season change on each individual facility? Or is this a site-wide configuration flag, where we only have to toggle it once in one spot at the beginning of winter, and then EVERY facility has the winter warning text? The ticket isn't super clear on this but I don't feel comfortable updating our `facility` object schema just to flag some front end text that may very well identical site-wide. It will scale poorly the more facilities we have in our system.

It doesn't appear to be a site-wide toggle, at the very least the ticket title implied a need to set it for Seymour individually. I could see this being moved up to the parks level, now that you have pointed it out though.

**Comment by cameronpettit** [comment]
I understand what your code is doing. I am warning against changing our `facility` object schema to achieve feature flagging for showing winter warnings. Modifying the `facility` schema seems like overkill when it seems likely that this winter warning will be the same for all facilities during the winter season. If DUP inherits more parks/facilities in the future, toggling this winter warning becomes tedious. If this winter warning truly is identical across all facilities, I would feel more comfortable just adding and removing the `hidden` attribute in the front end HTML every season like we have been doing previously, and looking at implementing a scalable feature flagging service in a future ticket.

**Comment by wilwong89** [comment]
Per talking with Cam and Jess, I'll be reworking this to see if I can utilize the config service or fall back to putting a flag on the parks object. In any case it needs updating.

**Pull request closed without merging**
